# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 13:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('priority', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[(('aqua', '#7fdbff'), ('aqua', '#7fdbff')), (('black', '#111111'), ('black', '#111111')), (('blue', '#0074d9'), ('blue', '#0074d9')), (('fuchsia', '#f012be'), ('fuchsia', '#f012be')), (('gray', '#aaaaaa'), ('gray', '#aaaaaa')), (('green', '#2ecc40'), ('green', '#2ecc40')), (('lime', '#01ff70'), ('lime', '#01ff70')), (('maroon', '#85144b'), ('maroon', '#85144b')), (('navy', '#001f3f'), ('navy', '#001f3f')), (('olive', '#3d9970'), ('olive', '#3d9970')), (('orange', '#ff851b'), ('orange', '#ff851b')), (('purple', '#b10dc9'), ('purple', '#b10dc9')), (('red', '#ff4136'), ('red', '#ff4136')), (('silver', '#dddddd'), ('silver', '#dddddd')), (('teal', '#39cccc'), ('teal', '#39cccc')), (('yellow', '#ffdc00'), ('yellow', '#ffdc00')), (('white', '#ffffff'), ('white', '#ffffff'))], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('main_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='singers', to='songs.Section')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SingerPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_main_part', models.BooleanField(default=True)),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singer_parts', to='songs.Singer')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='songs', to='songs.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='SongFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_main_file', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_xml', models.BooleanField(default=False)),
                ('is_score', models.BooleanField(default=False)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='songs.Song')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SongPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='song_parts', to='songs.Section')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_parts', to='songs.Song')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='singerpart',
            name='song_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singer_parts', to='songs.SongPart'),
        ),
    ]
