# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songpart',
            name='song',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='song_parts', to='songs.Song'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='folder',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='songpart',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='song_parts', to='songs.Section'),
        ),
    ]
