# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order_key']},
        ),
        migrations.AddField(
            model_name='section',
            name='order_key',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
