# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20170618_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='score_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='songs.SongFile'),
        ),
        migrations.AddField(
            model_name='songfile',
            name='is_score',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='singerpart',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singer_parts', to='songs.Singer'),
        ),
    ]
