# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20170618_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singerpart',
            old_name='main',
            new_name='is_main',
        ),
        migrations.AlterField(
            model_name='section',
            name='color',
            field=models.CharField(choices=[(('aqua', '#7fdbff'), ('aqua', '#7fdbff')), (('black', '#111111'), ('black', '#111111')), (('blue', '#0074d9'), ('blue', '#0074d9')), (('fuchsia', '#f012be'), ('fuchsia', '#f012be')), (('gray', '#aaaaaa'), ('gray', '#aaaaaa')), (('green', '#2ecc40'), ('green', '#2ecc40')), (('lime', '#01ff70'), ('lime', '#01ff70')), (('maroon', '#85144b'), ('maroon', '#85144b')), (('navy', '#001f3f'), ('navy', '#001f3f')), (('olive', '#3d9970'), ('olive', '#3d9970')), (('orange', '#ff851b'), ('orange', '#ff851b')), (('purple', '#b10dc9'), ('purple', '#b10dc9')), (('red', '#ff4136'), ('red', '#ff4136')), (('silver', '#dddddd'), ('silver', '#dddddd')), (('teal', '#39cccc'), ('teal', '#39cccc')), (('yellow', '#ffdc00'), ('yellow', '#ffdc00')), (('white', '#ffffff'), ('white', '#ffffff'))], max_length=6),
        ),
    ]
