# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_auto_20170727_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singerpart',
            old_name='is_main',
            new_name='is_main_part',
        ),
    ]
